name: juice_notifications_example
description: Demo app for juice_notifications.
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ^3.5.4
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  juice:
    path: ../../juice
  juice_notifications:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
